#!/usr/bin/env bash
# Requirements:

# Install nginx on your web-01
sudo apt-get -y update
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

sudo service nginx restart
