#!/usr/bin/env bash
# A script that loops through 1 to 10 using while loop

counter=1

while [ $counter -le 10 ]; do
	if [ $counter -eq 4 ]; then
		echo "bad luck"
	elif [ $counter -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	((counter++))
done
